### ISSUE TITLE
Enhancement: Show IP Address on System or settings screen

### ISSUE THREAD

**Issue by Mikumiku747** [woutervanwijk/Pi-MusicBox#269] opened 2015-04-09 02:34 UTC
I was hoping there would be a way to show the IP address of the device on the system or settings screens, that way when you connect the musicbox to a new wired netwrok, you can use one device to find the IP (By going to musibox.local) and then you can use that address if you have an android device.

**Comment by kingosticks** [comment] 2015-04-09 07:00
There is an issue for this already somewhere.

**Comment by kingosticks** [comment] 2015-04-17 13:01
Duplicate of https://github.com/woutervanwijk/Mopidy-MusicBox-Webclient/issues/67

**Closed by kingosticks** 2015-04-17 13:01 UTC
