### ISSUE TITLE
Authenticate Mopidy with music services. Error: 401 - Unauthorized

### ISSUE THREAD

**Issue by mvaneijgen** [woutervanwijk/Pi-MusicBox#228] opened 2015-02-23 11:38 UTC
When going to https://www.mopidy.com/authenticate/# and hitting the big orange button "Connect with Soundcloud" I get the error "Error: 401 - Unauthorized"

**Comment by jodal** [comment] 2015-02-23 11:44
Works for me.

Where do you see the error message? In the main browser window or in the popup?

**Comment by mvaneijgen** [comment] 2015-02-23 11:48
In a popup 
https://www.dropbox.com/s/y26aabt6ayqs9am/modpi.mp4?dl=0

**Comment by jodal** [comment] 2015-02-23 11:51
It went at bit fast at the end... after clicking the Facebook login button, did you click "connect me" too, or did it go directly to the 401 error?

**Comment by mvaneijgen** [comment] 2015-02-23 11:52
I Hit the 'Connect' button and after that got the error

**Comment by jodal** [comment] 2015-02-23 12:03
Can you reproduce this in other browsers than Safari?

**Comment by mvaneijgen** [comment] 2015-02-23 12:08
No I can not. Chrome works.

**Comment by jodal** [comment] 2015-02-23 12:11
I don't have Safari available myself right this moment, but I'll hopefully have a look at this later. I've opened mopidy/mopidy-website#2 to track this issue. Feel free to close this one (I can't).

**Closed** 2015-02-23 12:15 UTC
