### ISSUE TITLE
Doesn't support hostnames longer than 8 characters

### ISSUE THREAD

**Issue by osos** [woutervanwijk/Pi-MusicBox#283] opened 2015-05-10 17:16 UTC
Using the settings file to configure the hostname to a name longer than 8 characters is truncated on a fresh install.

**Comment by kingosticks** [comment] 2015-05-10 17:30
This is a duplicate of https://github.com/woutervanwijk/Pi-MusicBox/issues/70 and there is now a comment to this effect in settings.ini.

**Comment by kingosticks** [comment] 2015-05-26 14:59
We could technically remove the restriction and leave a comment that suggests shortening the name if you run into problems. But since people tend to not bothering reading the comments it'll just create more support work. So we'll keep it simple and we'll keep it working.

**Closed by kingosticks** 2015-05-26 14:59 UTC
